vim.api.nvim_set_keymap("", "F", "^", {})
vim.api.nvim_set_keymap("", "T", "$", {})
vim.api.nvim_set_keymap("", "n", "nzz", {})
vim.api.nvim_set_keymap("", "N", "Nzz", {})
vim.api.nvim_set_keymap("", "*", "*zz", {})
vim.api.nvim_set_keymap("", "#", "#zz", {})
vim.api.nvim_set_keymap("", "g#", "g*zz", {})
vim.api.nvim_set_keymap("v", "<TAB>", ">gc", {})
vim.api.nvim_set_keymap("v", "<S-TAB>", "<gc", {})
vim.api.nvim_set_keymap("v", "<S-j>", ":m'>+<cr>`<my`>mzgv`yo`z", {})
vim.api.nvim_set_keymap("v", "<S-k>", ":m'<-2<cr>`>my`<mzgv`yo`z", {})
vim.api.nvim_set_keymap("", "<leader>cd", ":cd %:p:h<CR>:pwd<CR>", {})
vim.api.nvim_set_keymap("", "<leader>bp", ":bp<CR>", {})
vim.api.nvim_set_keymap("", "<leader>bn", ":bn<CR>", {})
vim.api.nvim_set_keymap("", "<leader>nh", ":noh<CR>", {})
