name: "Nix-Build"

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.nix'
      - 'Makefile'
      - 'nix-conf'
      - 'nix-runner'
  push:
    branches:
      - main
    paths:
      - '**.nix'
      - 'Makefile'
      - 'nix-conf'
      - 'nix-runner'
jobs:
  tests:
    env:
      CHANNEL: 21.11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - run: make gen && make test
    - run: make lint-check
